import { z } from "zod";
import { uid } from "../utils/index";

/**
 * Lite stream schema.
 * Render-only — no prompts, no async transforms, no providers.
 *
 * A stream tree is rooted at `root`. Folders contain children.
 * Leaf streams (video/audio/image/component) carry timing on their base
 * fields (start/end/duration/startFrom/endAt) describing when they appear
 * on the timeline.
 *
 * Subtitles are a root-level overlay: root.subtitle points to a VTT file
 * that covers the full video duration. Generated by the TTS pipeline.
 */

/**
 * Leaf timing lives directly on BaseShape (start/end/duration/startFrom/endAt).
 * The old `actions[]` array has been removed — every leaf occupies exactly one
 * span on its parent's timeline. `end` is the source of truth for duration;
 * `duration` is a normalized convenience (end = start + duration when end is
 * absent). `loop`/`volume`/`style` moved onto the stream type itself.
 */

export const eventSpec = z.object({
  when: z.string().describe("'start' | 'end' | '50%' | '2.5s'"),
  state: z.string().describe("JS expression evaluated with registered components in scope"),
});
export type EventSpec = z.infer<typeof eventSpec>;

const BaseShape = {
  id: z.string().default(() => uid()),
  instruction: z.string().optional().describe("visual intent or style guide for this node (not rendered)"),
  src: z.string().optional(),
  style: z.string().optional().describe("inline css"),
  visible: z.boolean().default(true),
  isBackground: z.boolean().optional(),
  start: z.number().min(0).default(0).describe("seconds, relative to parent timeline (0 inside series parents)"),
  end: z.number().min(0).optional().describe("seconds, relative to parent timeline — source of truth for duration"),
  duration: z.number().min(0).optional().describe("convenience; normalized to end = start + duration when end is absent"),
  startFrom: z.number().min(0).optional().describe("trim seconds from source start (video/audio)"),
  endAt: z.number().min(0).optional().describe("trim seconds at source end (video/audio)"),
  durationInSeconds: z.number().optional().describe("set by engine; do not edit by hand"),
  on: eventSpec.optional().describe("event that fires at a specific frame, mutating registered component state"),
};

export const base = z.object(BaseShape);

export const folder = base.extend({
  type: z.literal("folder").default("folder"),
  isSeries: z.boolean().optional(),
  transition: z.enum(["fade", "slide", "wipe", "flip", "clockWipe"]).optional(),
  transitionTime: z.number().min(0.1).max(5).default(0.5),
  shadow: z.number().min(0).optional(),
  children: z.array(z.lazy((): z.ZodTypeAny => stream)).default(() => []),
});
export type Folder = z.infer<typeof folder>;

export const subtitleOverlay = z.object({
  src: z.string().optional().describe("path or URL to VTT file covering the full video duration; omitted when no subtitles are available"),
  style: z.string().optional().describe("inline css for the overlay container"),
  fontSize: z.union([z.number(), z.string()]).optional(),
  type: z.string().optional().describe("caption animation type: bounce, fade, typewriter, colorful, glowing, neon, etc."),
  fontFamily: z.string().optional().describe("font family for subtitle text"),
  fontStyle: z.string().optional().describe("font style: normal, italic, bold, bold italic, etc."),
});
export type SubtitleOverlay = z.infer<typeof subtitleOverlay>;

export const root = folder.extend({
  id: z.literal("root").default("root"),
  type: z.literal("root").default("root"),
  width: z.number().int().positive().default(1080),
  height: z.number().int().positive().default(1920),
  fps: z.number().int().positive().default(30),
  instruction: z.string().optional(),
  metadata: z.string().optional(),
  seed: z.number().optional().describe("global seed for TTI/TTV generation; substituted into CLI {seed} placeholder"),
  stylesheet: z.string().optional().describe("global css; selectors use .type and .name"),
  subtitle: subtitleOverlay.optional().describe("global subtitle overlay; src is a VTT file with absolute timestamps"),
  /**
   * Component registry source for react-jsx-parser.
   *
   * Two runtime forms (the descriptive ImportEntry[] array is resolved by the
   * compiler/server BEFORE reaching here):
   *   - string: URL to a pre-bundled ESM module whose named exports are the
   *             components (set by the player server after bundling frontmatter
   *             `imports:`).
   *   - object: inline `{ Name: ComponentType }` map for programmatic use.
   *
   * Without this field declared, zod's default `.strip()` removes it during
   * `root.parse()`, so the registry never loads at runtime.
   */
  imports: z
    .union([z.string(), z.record(z.string(), z.any())])
    .optional()
    .describe("component registry: URL to a pre-bundled module (string) or inline component map (object)"),
});
export type Root = z.infer<typeof root>;

export const video = base.extend({
  type: z.literal("video").default("video"),
  src: z.string().optional(),
  volume: z.number().min(0).max(1).default(1),
  playbackRate: z.number().optional(),
  width: z.number().default(1080),
  height: z.number().default(1920),
});
export type Video = z.infer<typeof video>;

export const audio = base.extend({
  type: z.literal("audio").default("audio"),
  src: z.string().optional(),
  volume: z.number().min(0).max(1).default(1),
  foreground: z.boolean().optional().describe("ducks parent video audio while playing"),
  speaker: z.string().optional().describe("speaker name for multi-turn dialogue; set by resolveDialogue"),
});
export type Audio = z.infer<typeof audio>;

export const image = base.extend({
  type: z.literal("image").default("image"),
  src: z.string().optional(),
  fit: z.enum(["contain", "cover", "fill"]).default("contain"),
});
export type Image = z.infer<typeof image>;

/**
 * Component node — JSX usage expression compiled at runtime.
 *
 * The `jsx` field is a React JSX expression (e.g. "<BarChart data={...} />").
 * Component tag names are resolved from the `components` map at runtime in compose context.

 */
export const component = base.extend({
  type: z.literal("component").default("component"),
  jsx: z.string().describe("usage JSX expression compiled at runtime; tag names resolved from imports"),
  data: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])).optional().describe("extra variables (e.g. from ~~~md source code fences) available in JSX scope"),
});
export type Component = z.infer<typeof component>;

// ---------------------------------------------------------------------------
// Effect — CSS keyframe animation wrapper
// ---------------------------------------------------------------------------
export const effect = base.extend({
  type: z.literal("effect").default("effect"),
  animation: z.string().optional().describe("builtin keyframe name or 'custom'"),
  animationTimingFunction: z
    .enum(["linear", "ease", "ease-in", "ease-out", "ease-in-out"])
    .optional(),
  animationIterationCount: z.number().default(1),
  customKeyframes: z
    .record(z.string(), z.record(z.string(), z.string()))
    .optional()
    .describe('inline keyframes: { "0": { opacity: "0" }, "100": { opacity: "1" } }'),
  children: z.array(z.lazy((): z.ZodTypeAny => stream)).default(() => []),
});
export type Effect = z.infer<typeof effect>;

// ---------------------------------------------------------------------------
// Rhythm — audio loop with beat-synced children
// ---------------------------------------------------------------------------
export const rhythm = base.extend({
  type: z.literal("rhythm").default("rhythm"),
  src: z.string().optional().describe("audio file for beat playback"),
  volume: z.number().min(0).max(1).default(1),
  spots: z.array(z.number()).optional().describe("pre-computed beat timestamps in seconds"),
  children: z.array(z.lazy((): z.ZodTypeAny => stream)).default(() => []),
});
export type Rhythm = z.infer<typeof rhythm>;

// ---------------------------------------------------------------------------
// Include — references an external video JSON file by src.
// The referenced file can be either:
//   - A stream tree JSON (has `type: "root"` or `root` property)
//   - A scene-based video.json (has `meta` and `scenes`)
//
// Usage:
//   { type: "include", src: "./path/to/video.json", start: 0, end: 5 }
//
// Falls back to inline `children` if `src` is not set (legacy behavior).
// ---------------------------------------------------------------------------
export const include = base.extend({
  type: z.literal("include").default("include"),
  src: z.string().optional().describe("path or URL to video JSON file (stream tree or scene-based)"),
  volume: z.number().min(0).max(1).default(1),
  children: z.array(z.lazy((): z.ZodTypeAny => stream)).default(() => []),
  imports: z.string().optional().describe("component bundle URL for sub-video (set by engine)"),
});
export type Include = z.infer<typeof include>;

// ---------------------------------------------------------------------------
// Scene — descriptive container node for storyboarding.
// A scene is a visual grouping node with metadata (name, description) that
// renders its children like a folder. It exists so UI tools can display
// high-level storyboard cards without needing to understand the full stream
// tree. The engine treats it identically to a folder.
//
// Usage:
//   { type: "scene", name: "Intro", description: "Opening hook",
//     children: [{ type: "component", componentName: "BigStatement", ... }] }
//
// Parent folder's isSeries controls sequencing (same as folder children).
// ---------------------------------------------------------------------------
export const scene = base.extend({
  type: z.literal("scene").default("scene"),
  name: z.string().optional().describe("scene name from heading"),
  title: z.string().optional().describe("scene display title"),
  instruction: z.string().optional().describe("scene visual intent for storyboard UI"),
  children: z.array(z.lazy((): z.ZodTypeAny => stream)).default(() => []),
  durationInSeconds: z.number().optional().describe("set by engine; do not edit by hand"),
});
export type Scene = z.infer<typeof scene>;

// ---------------------------------------------------------------------------
// Map — animated route visualization
// ---------------------------------------------------------------------------
export const mapWaypoint = z.object({
  lat: z.number(),
  lng: z.number(),
  label: z.string().optional(),
  media: z.string().optional().describe("image/video src for waypoint marker"),
});

export const mapStream = base.extend({
  type: z.literal("map").default("map"),
  waypoints: z.array(mapWaypoint).default(() => []),
  routeColor: z.string().default("#4285F4"),
  routeWeight: z.number().default(4),
  zoom: z.number().default(10),
  center: z.object({ lat: z.number(), lng: z.number() }).optional().describe("map view center (defaults to first waypoint)"),
  mapType: z.enum(["roadmap", "satellite", "hybrid", "terrain"]).default("roadmap").describe("Google Maps style"),
  travelMode: z.enum(["DRIVING", "WALKING", "BICYCLING", "TRANSIT"]).default("DRIVING").describe("Directions API travel mode"),
  routeMarker: z.string().default("🚗").describe("emoji/character for the animated traveling marker"),
  googleMapsApiKey: z.string().optional().describe("injected by compiler from GOOGLE_MAPS_API_KEY env var"),
});
export type MapStream = z.infer<typeof mapStream>;

// ---------------------------------------------------------------------------
// Discriminated union
// ---------------------------------------------------------------------------
export const stream = z.discriminatedUnion("type", [
  root,
  folder,
  video,
  audio,
  image,
  component,
  effect,
  rhythm,
  mapStream,
  include,
  scene,
]);
export type Stream = z.infer<typeof stream>;


